---
title: "R Notebook"
output: html_notebook
---

```{r}
library(openxlsx)
```

```{r}
wb <- createWorkbook()
addWorksheet(wb, sheetName = "S1")
addWorksheet(wb, sheetName = "S2")
addWorksheet(wb, sheetName = "S3")
activeSheet(wb) <- 1
saveWorkbook(wb, "a.xlsx", overwrite = TRUE)
```

```{r}
as <- activeSheet(wb) 
as
```

```{r}
addCreator(wb, "WW")
```

```{r}
x <- mtcars[1:6, ]
x
writeData(wb, 1, x, startCol = 2, startRow = 3, rowNames = TRUE)
saveWorkbook(wb, "a.xlsx", overwrite = TRUE)
```


```{r}
st1 <- createStyle(fgFill = "#DCE6F1", valign="center", halign = "CENTER", textDecoration = "italic", border = c("Top", "Bottom"), borderStyle=c("thin", "thick"))
x <- mtcars[1:6, ]
x
setRowHeights(wb, 1, rows = 3, heights = 40)
setColWidths(wb, "S1", cols=2, widths = 20 )
writeData(wb, 1, x, startCol = 2, startRow = 3, rowNames = TRUE, headerStyle = st1)
saveWorkbook(wb, "a.xlsx", overwrite = TRUE)

```

```{r}
st2 <- createStyle(fgFill = "#DCE6F1", halign="center")
mergeCells(wb, "S1", cols = 2:13, rows = 1)
addStyle(wb, "S1", st2, 1, 2, gridExpand = FALSE, stack = FALSE)
writeData(wb, 1, c("ala ma kota"), startCol = 2, startRow = 1, rowNames = FALSE)
saveWorkbook(wb, "a.xlsx", overwrite = TRUE)
```


```{r}
# colnames(a1) <- c('desc1','mpg1','cyl1','disp1','hp1','drat1','wt1','qsec1','vs1','am1','gear1','carb1') 
wiersz <- 4
nazwa_pliku <- "a.xlsx"
wb <- loadWorkbook(nazwa_pliku)
dane <- read.xlsx(nazwa_pliku, sheet = "S1", startRow=wiersz, colNames=FALSE, skipEmptyRows = FALSE, cols = c(1:5))
colnames(dane) <- c('desc1','mpg1','cyl1','disp1') 
writeData(wb, "S2", dane, startCol = 1, startRow = 1, rowNames = FALSE, colNames = TRUE)

writeData(wb, "S2", c(108), startCol = 8, startRow = 1, rowNames = FALSE, colNames = FALSE)

posStyle <- createStyle(fontColour = "#006100", bgFill = "#C6EFCE")
conditionalFormatting(wb, "S2",
cols = 4,
rows = 2:7, rule = " > $H$1", style = posStyle, type = "expression"
)

saveWorkbook(wb, nazwa_pliku, overwrite = TRUE)

```

